sonar.projectKey=LitchillUseCases
sonar.host.url=http://localhost:9000
sonar.login=sqp_45222d5916797ce00db9e7523bcd21450ec4f573
sonar.sources=functions
sonar.exclusions=**/node_modules/**, **/functions/tests/**, **/*.test.ts, **/*.spec.ts
sonar.language=ts
sonar.sourceEncoding=UTF-8
